<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 24.08.2020
 * Time: 18:28
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;


class AppController extends Controller
{
    public function beforeAction($action)
    {
        $this->view->title = Yii::$app->name;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
