<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 24.08.2020
 * Time: 14:10
 */

namespace app\models;


use yii\db\ActiveRecord;

class Product extends ActiveRecord
{
    public static function tableName()
    {
        //return parent::tableName(); // TODO: Change the autogenerated stub
        return 'product';
    }
}